site_name: Airdot-Deployer Docs

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Airdot-Deployer Docs: index.md
  - tutorials.md
  - how-to-guides.md
  - reference.md
  - explanation.md